local p = require("themes.apprentice.palette")

return {
  Normal = { fg = p.fg, bg = p.bg },
  NormalNC = { fg = p.fg, bg = p.bg },
  NormalFloat = { fg = p.fg, bg = p.black },
  FloatBorder = { fg = p.gray_light, bg = p.black },
  FloatTitle = { fg = p.yellow, bg = p.black },
  Terminal = { link = "Normal" },

  Cursor = { fg = p.bg, bg = p.fg },
  CursorLine = { bg = p.bg_alt },
  CursorColumn = { bg = p.bg_alt },
  ColorColumn = { bg = p.black },
  LineNr = { fg = p.gray_light, bg = p.black },
  CursorLineNr = { fg = p.yellow, bg = p.bg_alt, bold = true },
  SignColumn = { fg = p.gray_light, bg = p.black },
  FoldColumn = { fg = p.gray_light, bg = p.black },
  Folded = { fg = p.gray_light, bg = p.black },
  WinSeparator = { fg = p.bg_highlight, bg = p.bg },
  VertSplit = { link = "WinSeparator" },

  Visual = { bg = p.bg_highlight },
  VisualNOS = { bg = p.bg_highlight, underline = true },
  Search = { fg = p.bg, bg = p.yellow },
  CurSearch = { fg = p.bg, bg = p.red },
  IncSearch = { fg = p.bg, bg = p.red },
  MatchParen = { fg = p.yellow, bg = p.black, bold = true },

  Pmenu = { fg = p.fg, bg = p.bg_highlight },
  PmenuSel = { fg = p.bg, bg = p.cyan },
  PmenuSbar = { bg = p.gray },
  PmenuThumb = { bg = p.cyan },
  WildMenu = { fg = p.bg, bg = p.blue_light },

  StatusLine = { fg = p.bg, bg = p.yellow_light },
  StatusLineNC = { fg = p.yellow_light, bg = p.bg_highlight },
  TabLine = { fg = p.yellow_light, bg = p.bg_highlight },
  TabLineFill = { fg = p.bg_highlight, bg = p.bg_highlight },
  TabLineSel = { fg = p.bg, bg = p.yellow_light },

  Directory = { fg = p.cyan_light },
  EndOfBuffer = { fg = p.gray },
  NonText = { fg = p.gray },
  SpecialKey = { fg = p.gray },
  Conceal = { fg = p.fg },
  Title = { fg = p.yellow, bold = true },
  Question = { fg = p.green_light },
  MoreMsg = { fg = p.cyan },
  ModeMsg = { fg = p.green_light, reverse = true },
  WarningMsg = { fg = p.red },
  ErrorMsg = { fg = p.red, bg = p.bg, reverse = true },

  Comment = { fg = p.gray_light, italic = true },
  Constant = { fg = p.red_light },
  String = { fg = p.green_light },
  Character = { link = "String" },
  Number = { link = "Constant" },
  Boolean = { link = "Constant" },
  Float = { link = "Constant" },
  Identifier = { fg = p.blue },
  Function = { fg = p.yellow },
  Statement = { fg = p.blue_light },
  Conditional = { link = "Statement" },
  Repeat = { link = "Statement" },
  Label = { fg = p.cyan_light },
  Operator = { fg = p.blue_light },
  Keyword = { link = "Statement" },
  Exception = { link = "Statement" },
  PreProc = { fg = p.cyan },
  Include = { link = "PreProc" },
  Define = { link = "PreProc" },
  Macro = { link = "PreProc" },
  PreCondit = { link = "PreProc" },
  Type = { fg = p.magenta_light },
  StorageClass = { link = "Type" },
  Structure = { link = "Type" },
  Typedef = { link = "Type" },
  Special = { fg = p.green },
  SpecialChar = { link = "Special" },
  Tag = { link = "Special" },
  Delimiter = { fg = p.gray_light },
  SpecialComment = { link = "Special" },
  Debug = { link = "Special" },
  Underlined = { fg = p.cyan, underline = true },
  Ignore = { fg = p.gray },
  Error = { fg = p.red, bold = true },
  Todo = { fg = p.yellow, bg = p.bg_highlight, bold = true },

  DiffAdd = { fg = p.diff_add, bg = p.bg_alt, reverse = true },
  DiffChange = { fg = p.diff_change, bg = p.bg_alt },
  DiffDelete = { fg = p.diff_delete, bg = p.bg_alt, reverse = true },
  DiffText = { fg = p.diff_text, bg = p.bg_highlight, bold = true },
  Added = { fg = p.green_light },
  Changed = { fg = p.yellow },
  Removed = { fg = p.red },

  SpellBad = { sp = p.red, undercurl = true },
  SpellCap = { sp = p.cyan_light, undercurl = true },
  SpellLocal = { sp = p.green, undercurl = true },
  SpellRare = { sp = p.red_light, undercurl = true },

  DiagnosticError = { fg = p.red },
  DiagnosticWarn = { fg = p.red_light },
  DiagnosticInfo = { fg = p.blue_light },
  DiagnosticHint = { fg = p.cyan_light },
  DiagnosticOk = { fg = p.green_light },
  DiagnosticSignError = { link = "DiagnosticError" },
  DiagnosticSignWarn = { link = "DiagnosticWarn" },
  DiagnosticSignInfo = { link = "DiagnosticInfo" },
  DiagnosticSignHint = { link = "DiagnosticHint" },
  DiagnosticVirtualTextError = { fg = p.red, bg = p.black },
  DiagnosticVirtualTextWarn = { fg = p.red_light, bg = p.black },
  DiagnosticVirtualTextInfo = { fg = p.blue_light, bg = p.black },
  DiagnosticVirtualTextHint = { fg = p.cyan_light, bg = p.black },
  DiagnosticUnderlineError = { sp = p.red, undercurl = true },
  DiagnosticUnderlineWarn = { sp = p.red_light, undercurl = true },
  DiagnosticUnderlineInfo = { sp = p.blue_light, undercurl = true },
  DiagnosticUnderlineHint = { sp = p.cyan_light, undercurl = true },

  ["@comment"] = { link = "Comment" },
  ["@constant"] = { link = "Constant" },
  ["@constant.builtin"] = { fg = p.red_light, bold = true },
  ["@string"] = { link = "String" },
  ["@character"] = { link = "Character" },
  ["@number"] = { link = "Number" },
  ["@boolean"] = { link = "Boolean" },
  ["@float"] = { link = "Float" },
  ["@function"] = { link = "Function" },
  ["@function.builtin"] = { fg = p.yellow, bold = true },
  ["@function.call"] = { link = "Function" },
  ["@constructor"] = { fg = p.magenta_light },
  ["@keyword"] = { link = "Statement" },
  ["@keyword.function"] = { link = "Statement" },
  ["@keyword.return"] = { fg = p.blue_light, bold = true },
  ["@conditional"] = { link = "Conditional" },
  ["@repeat"] = { link = "Repeat" },
  ["@operator"] = { link = "Operator" },
  ["@type"] = { link = "Type" },
  ["@type.builtin"] = { fg = p.magenta_light, bold = true },
  ["@variable"] = { fg = p.fg },
  ["@variable.builtin"] = { fg = p.red_light },
  ["@parameter"] = { fg = p.fg },
  ["@property"] = { fg = p.cyan_light },
  ["@field"] = { link = "@property" },
  ["@module"] = { fg = p.blue },
  ["@namespace"] = { link = "@module" },
  ["@punctuation"] = { fg = p.gray_light },
  ["@punctuation.bracket"] = { fg = p.gray_light },
  ["@punctuation.delimiter"] = { fg = p.gray_light },
  ["@tag"] = { fg = p.blue_light },
  ["@tag.attribute"] = { fg = p.cyan_light },
  ["@tag.delimiter"] = { fg = p.gray_light },
  ["@markup.heading"] = { link = "Title" },
  ["@markup.strong"] = { bold = true },
  ["@markup.italic"] = { italic = true },
  ["@markup.link"] = { fg = p.cyan, underline = true },
  ["@markup.raw"] = { fg = p.green_light },

  ["@lsp.type.class"] = { link = "Type" },
  ["@lsp.type.enum"] = { link = "Type" },
  ["@lsp.type.function"] = { link = "Function" },
  ["@lsp.type.interface"] = { link = "Type" },
  ["@lsp.type.macro"] = { link = "Macro" },
  ["@lsp.type.method"] = { link = "Function" },
  ["@lsp.type.namespace"] = { link = "@module" },
  ["@lsp.type.parameter"] = { link = "@parameter" },
  ["@lsp.type.property"] = { link = "@property" },
  ["@lsp.type.variable"] = { link = "@variable" },
  ["@lsp.mod.deprecated"] = { fg = p.gray_light, strikethrough = true },

  -- TelescopeNormal = { fg = p.fg, bg = p.bg },
  -- TelescopeBorder = { fg = p.gray_light, bg = p.bg },
  -- TelescopePromptNormal = { fg = p.fg, bg = p.black },
  -- TelescopePromptBorder = { fg = p.gray_light, bg = p.black },
  -- TelescopePromptTitle = { fg = p.bg, bg = p.cyan },
  -- TelescopePreviewTitle = { fg = p.bg, bg = p.green },
  -- TelescopeResultsTitle = { fg = p.bg, bg = p.blue },
  -- TelescopeSelection = { fg = p.yellow, bg = p.bg_highlight },
  -- TelescopeMatching = { fg = p.red_light, bold = true },

  -- DashboardHeader = { fg = p.blue_light },
  -- DashboardFooter = { fg = p.yellow_light },
  -- DashboardShortCut = { fg = p.yellow },
  -- DashboardShortCutIcon = { fg = p.cyan_light },
  -- DashboardProjectTitle = { fg = p.cyan_light, bold = true },
  -- DashboardProjectTitleIcon = { fg = p.cyan_light },
  -- DashboardProjectIcon = { fg = p.blue_light },
  -- DashboardMruTitle = { fg = p.green_light, bold = true },
  -- DashboardMruIcon = { fg = p.green_light },
  -- DashboardFiles = { fg = p.fg },

}
