#   __  __   __   ______  ______  __  __
#  /\ \/ /  /\ \ /\__  _\/\__  _\/\ \_\ \
#  \ \  _"-.\ \ \\/_/\ \/\/_/\ \/\ \____ \
#   \ \_\ \_\\ \_\  \ \_\   \ \_\ \/\_____\
#    \/_/\/_/ \/_/   \/_/    \/_/  \/_____/

include colors.conf

shell /bin/bash --login
shell_integration enabled

enable_audio_bell no

font_family CaskaydiaMono Nerd Font Mono
font_size   14.0

background_opacity 1.0

tab_bar_style powerline

scrollback_pager nvim +'setlocal buftype=nofile bufhidden=wipe noswapfile nomodifiable' +normal\!G -

# ---------------------------------------------------------------------------- #
#                                     MOUSE                                    #
# ---------------------------------------------------------------------------- #

mouse_map ctrl+shift+left press ungrabbed mouse_selection rectangle
mouse_map ctrl+shift+left triplepress ungrabbed mouse_selection line_from_point

# ---------------------------------------------------------------------------- #
#                                   SHORTCUTS                                  #
# ---------------------------------------------------------------------------- #

# Previous prompt
map ctrl+t>n scroll_to_prompt -1
# Next prompt
map ctrl+t>o scroll_to_prompt 1

# Open URL from the visible screen
map ctrl+t>u kitten hints --type url
# Select a filepath from screen and paste it into the prompt
map ctrl+t>f kitten hints --type path --program -
# Copy last command output to clipboard
map ctrl+t>y copy_last_command_output

map ctrl+t>h show_scrollback

map ctrl+KP_Add change_font_size all +2.0
map ctrl+KP_Subtract change_font_size all -2.0
map ctrl+KP_Multiply change_font_size all 0

map ctrl+Up scroll_page_up
map ctrl+Down scroll_page_down

map --new-mode resize --timeout 5.0 ctrl+shift+r

map --mode resize i resize_window taller 10
map --mode resize o resize_window wider 10
map --mode resize e resize_window shorter 10
map --mode resize n resize_window narrower 10

map --mode resize r resize_window reset
map --mode resize esc pop_keyboard_mode
map --mode resize enter pop_keyboard_mode

# ----------------------------- WINDOW MANAGEMENT ---------------------------- #

# Window management
map ctrl+m toggle_layout stack
map ctrl+enter new_window
map ctrl+w close_window

# Focus movement
map ctrl+alt+i neighboring_window up
map ctrl+alt+o neighboring_window right
map ctrl+alt+e neighboring_window down
map ctrl+alt+n neighboring_window left

# Move windows
map ctrl+shift+i move_window up
map ctrl+shift+o move_window right
map ctrl+shift+e move_window down
map ctrl+shift+n move_window left

# Resize windows
map alt+i resize_window taller 10
map alt+o resize_window wider 10
map alt+e resize_window shorter 10
map alt+n resize_window narrower 10

# ------------------------------ TAB MANAGEMENT ------------------------------ #

map ctrl+shift+w close_tab

map ctrl+shift+enter new_tab_with_cwd
map ctrl+t>tab next_tab
map ctrl+t>shift+tab previous_tab

map ctrl+1 goto_tab 1
map ctrl+2 goto_tab 2
map ctrl+3 goto_tab 3

map ctrl+t>. move_tab_forward
map ctrl+t>, move_tab_backward
