#!/bin/bash
#   ______   ______   ______  __     __   __    __
#  /\  == \ /\  ___\ /\  == \/\ \  _ \ \ /\ "-./  \
#  \ \  __< \ \___  \\ \  _-/\ \ \/ ".\ \\ \ \-./\ \
#   \ \_____\\/\_____\\ \_\   \ \__/".~\_\\ \_\ \ \_\
#    \/_____/ \/_____/ \/_/    \/_/   \/_/ \/_/  \/_/

pgrep -x sxhkd > /dev/null || sxhkd &

# ---------------------------------------------------------------------------- #
#                                    GENERAL                                   #
# ---------------------------------------------------------------------------- #

bspc monitor -d I II III IV V

bspc config border_width          2
bspc config window_gap            12

bspc rule -a Zathura state=tiled
bspc rule -a firefox desktop='^1'

bspc config top_padding           30
bspc config bottom_padding        5
bspc config left_padding          5
bspc config right_padding         5

bspc config normal_border_color   "#BCBCBC"
bspc config focused_border_color  "#FFFFFF"

bspc config split_ratio             0.52

bspc config single_monocle          true
bspc config borderless_monocle      true
bspc config gapless_monocle         true

bspc config focus_follows_pointer   true
bspc config pointer_follows_focus   false

# ---------------------------------------------------------------------------- #
#                                   AUTOSTART                                  #
# ---------------------------------------------------------------------------- #

$HOME/.config/polybar/launch.sh &
# dunst -config $HOME/.config/dunst/dunstrc &
picom -f &
nitrogen --restore &
numlockx on
# discord --start-minimized
xrandr --output Virtual1 --mode 1440x900
VBoxClient --clipboard
