#!/bin/bash
#  ______  ______   __     __   ______   ______       __    __   ______   __   __   __  __
# /\  == \/\  __ \ /\ \  _ \ \ /\  ___\ /\  == \     /\ "-./  \ /\  ___\ /\ "-.\ \ /\ \/\ \
# \ \  _-/\ \ \/\ \\ \ \/ ".\ \\ \  __\ \ \  __<     \ \ \-./\ \\ \  __\ \ \ \-.  \\ \ \_\ \
#  \ \_\   \ \_____\\ \__/".~\_\\ \_____\\ \_\ \_\    \ \_\ \ \_\\ \_____\\ \_\\"\_\\ \_____\
#   \/_/    \/_____/ \/_/   \/_/ \/_____/ \/_/ /_/     \/_/  \/_/ \/_____/ \/_/ \/_/ \/_____/


uptime="$(uptime -p | sed -e 's/up //g')"
host=$(cat /etc/hostname)

# ---------------------------------- OPTIONS --------------------------------- #

shutdown='󰐥'
reboot='󰜉'
lock=''
logout='󰍃'
yes='Yes'
no='No'

function rofi_cmd {
	rofi -dmenu \
		-p "Uptime: $uptime" \
		-mesg "Uptime: $uptime" \
		-theme power_menu.rasi
}

function confirm_cmd {
	rofi -theme-str 'window {location: center; anchor: center; fullscreen: false; width: 350px;}' \
		-theme-str 'mainbox {children: [ "message", "listview" ];}' \
		-theme-str 'listview {columns: 2; lines: 1;}' \
		-theme-str 'element-text {horizontal-align: 0.5;}' \
		-theme-str 'textbox {horizontal-align: 0.5;}' \
		-dmenu \
		-p 'Confirmation' \
		-mesg 'Are you sure?' \
		-theme power_menu.rasi
}


function confirm_exit {
	echo -e "$yes\n$no" | confirm_cmd
}

function run_rofi {
	echo -e "$lock\n$logout\n$reboot\n$shutdown" | rofi_cmd
}

function run_cmd {
	selected="$(confirm_exit)"
	if [[ "$selected" == "$yes" ]]; then
		if [[ $1 == '--shutdown' ]]; then
			sudo systemctl poweroff
		elif [[ $1 == '--reboot' ]]; then
			sudo systemctl reboot
		elif [[ $1 == '--logout' ]]; then
			bspc quit
		fi
	else
		exit 0
	fi
}

chosen="$(run_rofi)"
case ${chosen} in
	"$shutdown")
		run_cmd --shutdown;;
	"$reboot")
		run_cmd --reboot;;
	"$lock")
		i3lock;;
	"$logout")
		run_cmd --logout;;
esac
