#!/bin/bash


chosen=$(printf "  Power Off\n  Restart\n  Suspend\n  Hibernate\n  Log out\n  Lock" | rofi -dmenu -i -theme-str '@import "power_menu.rasi"')

case "$chosen" in
	"  Power Off") poweroff ;;
	"  Restart") reboot now ;;
	"  Suspend") systemctl suspend-then-hibernate ;;
	"  Hibernate") systemctl hibernate ;;
	"  Log Out") bspc quit ;;
	"  Lock") betterlockscreen -l ;;
	*) exit 1 ;;
esac
