#!/bin/bash

file=$HOME/.config/polybar/scripts/target_content

if [ -e "$file" ]; then
	ip_address=$(awk '{print $1}' "$file")
	machine_name=$(awk '{print $2}' "$file")

	if [ "$ip_address" ] && [ "$machine_name" ]; then
		echo " 󰓾 $ip_address - $machine_name "
	else
		echo " 󰓾 No target "
	fi
else
	echo "File $file not found"
fi
