backgroud: &background "#262626"
foregroud: &foreground "#BCBCBC"

black: &black     "#1C1C1C"
red: &red         "#AF5F5F"
green: &green     "#5F875F"
yellow: &yellow   "#87875F"
blue: &blue       "#5F87AF"
magenta: &magenta "#5F5F87"
cyan: &cyan       "#5F8787"
white: &white     "#6C6C6C"

general:
  # Commands to run when the WM has started. This is useful for running a
  # script or launching another application
  startup_commands: ["shell-exec zebar"]

  # Commands to run just before the WM is shutdown
  shutdown_commands: ["shell-exec taskkill /IM zebar.exe /F"]

  # Commands to run after the WM config is reloaded
  config_reload_commands: []

  # Whether to automatically focus windows underneath the cursor
  focus_follows_cursor: false

  # Whether to switch back and forth between the previously focused
  # workspace when focusing the current workspace
  toggle_workspace_on_refocus: false

  cursor_jump:
    # Whether to automatically move the cursor on the specified trigger
    enabled: true

    # Trigger for cursor jump:
    # - "monitor_focus": Jump when focus changes between monitors
    # - "window_focus": Jump when focus changes between windows
    trigger: "monitor_focus"

gaps:
  # Whether to scale the gaps with the DPI of the monitor
  scale_with_dpi: true

  inner_gap: "5px"

  outer_gap:
    top: "60px"
    right: "5px"
    bottom: "5px"
    left: "5px"

window_effects:
  # Visual effects to apply to the focused window
  focused_window:
    # Highlight the window with a colored border
    # ** Exclusive to Windows 11 due to API limitations
    border:
      enabled: true
      color: *white

    # Remove the title bar from the window"s frame. Note that this can
    # cause rendering issues for some applications
    hide_title_bar:
      enabled: false

    # Change the corner style of the window"s frame
    # ** Exclusive to Windows 11 due to API limitations
    corner_style:
      enabled: false
      # Allowed values: "square", "rounded", "small_rounded"
      style: "square"

  # Visual effects to apply to non-focused windows
  other_windows:
    border:
      enabled: true
      color: *foreground
    hide_title_bar:
      enabled: false
    corner_style:
      enabled: false
      style: "square"

window_behavior:
  # New windows are created in this state whenever possible
  # Allowed values: "tiling", "floating"
  initial_state: "tiling"

  # Sets the default options for when a new window is created. This also
  # changes the defaults for when the state change commands, like
  # `set-floating`, are used without any flags
  state_defaults:
    floating:
      # Whether to center floating windows by default
      centered: true

      # Whether to show floating windows as always on top
      shown_on_top: false

    fullscreen:
      # Maximize the window if possible. If the window does not have a
      # maximize button, then it will be fullscreen"ed normally instead
      maximized: false

      # Whether to show fullscreen windows as always on top
      shown_on_top: false

workspaces:
  - name:         "1"
    display_name: "ブ"
    keep_alive:   true

  - name:         "2"
    display_name: "ラ"
    keep_alive:   true

  - name:         "3"
    display_name: "ン"
    keep_alive:   true

  - name: "4"
    display_name: "ド"
    keep_alive: true

  - name: "5"
    display_name: "ン"
    keep_alive: true

window_rules:
  - commands: ["ignore"]
    match:
      # Ignores any Zebar windows
      - window_process: { equals: "zebar" }

      # Ignores picture-in-picture windows for browsers
      - window_title: { regex: "[Pp]icture.in.[Pp]icture" }
        window_class: { regex: "Chrome_WidgetWin_1|MozillaDialogClass" }

      # Ignore rules for various 3rd-party apps
      - window_process: { equals: "PowerToys" }
        window_class: { regex: 'HwndWrapper\[PowerToys\.PowerAccent.*?\]' }
      - window_process: { equals: "PowerToys" }
        window_title: { regex: ".*? - Peek" }
      - window_process: { equals: "Lively" }
        window_class: { regex: "HwndWrapper" }

  - commands: ["set-floating"]
    match:
      - window_process: { equals: "Taskmgr" }

  - commands: ["move --workspace 1"]
    match:
      - window_process: { regex: "msedge|firefox|chrome|brave" }

  - commands: ["move --workspace 4"]
    match:
      - window_process: { regex: "steamwebhelper|EpicGamesLauncher|Spotify|Amazon Music" }

binding_modes:
  - name: "resize"
    keybindings:
      - commands: ["resize --width -2%"]
        bindings: ["h", "left"]

      - commands: ["resize --width +2%"]
        bindings: ["l", "right"]

      - commands: ["resize --height +2%"]
        bindings: ["k", "up"]

      - commands: ["resize --height -2%"]
        bindings: ["j", "down"]

      - commands: ["wm-disable-binding-mode --name resize"]
        bindings: ["escape", "enter"]

  - name: "pause"
    keybindings:
      - commands: ["wm-disable-binding-mode --name pause"]
        bindings: ["alt+shift+p"]

keybindings:
  - commands: ["focus --direction left"]
    bindings: ["alt+h", "alt+left"]

  - commands: ["focus --direction right"]
    bindings: ["alt+l", "alt+right"]

  - commands: ["focus --direction up"]
    bindings: ["alt+k", "alt+up"]

  - commands: ["focus --direction down"]
    bindings: ["alt+j", "alt+down"]

  - commands: ["move --direction left"]
    bindings: ["alt+shift+h", "alt+shift+left"]

  - commands: ["move --direction right"]
    bindings: ["alt+shift+l", "alt+shift+right"]

  - commands: ["move --direction up"]
    bindings: ["alt+shift+k", "alt+shift+up"]

  - commands: ["move --direction down"]
    bindings: ["alt+shift+j", "alt+shift+down"]

  - commands: ["wm-enable-binding-mode --name resize"]
    bindings: ["alt+r"]

  - commands: ["wm-enable-binding-mode --name pause"]
    bindings: ["alt+shift+p"]

  - commands: ["toggle-tiling-direction"]
    bindings: ["alt+v"]

  - commands: ["toggle-floating --centered"]
    bindings: ["alt+f"] # ["alt+shift+space"]

  - commands: ["toggle-fullscreen"]
    bindings: ["alt+m"]

  - commands: ["close"]
    bindings: ["alt+w"]

  - commands: ["wm-reload-config"]
    bindings: ["alt+shift+r"]

  - commands: ["wm-redraw"]
    bindings: ["alt+shift+w"]

  - commands: ["shell-exec wt"]
    bindings: ["alt+enter"]

  - commands: ["focus --workspace 1"]
    bindings: ["alt+1"]

  - commands: ["focus --workspace 2"]
    bindings: ["alt+2"]

  - commands: ["focus --workspace 3"]
    bindings: ["alt+3"]

  - commands: ["focus --workspace 4"]
    bindings: ["alt+4"]

  - commands: ["focus --workspace 5"]
    bindings: ["alt+5"]

  - commands: ["move --workspace 1", "focus --workspace 1"]
    bindings: ["alt+shift+1"]

  - commands: ["move --workspace 2", "focus --workspace 2"]
    bindings: ["alt+shift+2"]

  - commands: ["move --workspace 3", "focus --workspace 3"]
    bindings: ["alt+shift+3"]

  - commands: ["move --workspace 4", "focus --workspace 4"]
    bindings: ["alt+shift+4"]

  - commands: ["move --workspace 5", "focus --workspace 5"]
    bindings: ["alt+shift+5"]
