#! /bin/sh
#   ______   __  __   ______   ______   ______  ______   ______
#  /\  ___\ /\ \_\ \ /\  __ \ /\  __ \ /\__  _\/\  ___\ /\  == \
#  \ \___  \\ \  __ \\ \ \/\ \\ \ \/\ \\/_/\ \/\ \  __\ \ \  __<
#   \/\_____\\ \_\ \_\\ \_____\\ \_____\  \ \_\ \ \_____\\ \_\ \_\
#    \/_____/ \/_/\/_/ \/_____/ \/_____/   \/_/  \/_____/ \/_/ /_/


time=$(date +%Y-%m-%d-%I-%M-%S)
geometry=`xrandr | head -n1 | cut -d',' -f2 | tr -d ' ,current'`
dir="$HOME/Pictures"
file="Shot_${time}_${geometry}.jpg"

# Create the folder in case it does not exist
if ! [ -d "$dir" ]; then
	mkdir -p $dir
fi

function notify() {
	if [[ -e $1 ]]; then
		notify-send -i $1 -t 5000 GrayShooter "Screenshot saved."
	else
		notify-send -t 5000 GrayShooter "Screenshot canceled."
	fi
}

function Shot() {
	cd "$dir"

	local filename="$file"
	if [[ "$2" == "-t" ]]; then
		filename="temp_captura.jpg"
	fi

	if [[ "$1" == "-f" ]]; then
		scrot -q 100 -o "$filename"
	else
		scrot -q 100 -o "$filename" -s
	fi

	cat $filename | xclip -selection clipboard -t image/png
	notify "$dir/$filename"
}

function run() {
	if [[ "$1" != "-f" && "$1" != "-s" ]]; then
		echo "Available options: -n -s"
		exit 0
	fi

	Shot $1 $2
}

run $1 $2
