#!/bin/bash

get_value() {
    command="$1"
    result=$(eval "$command")
    echo "$result"
}

run_command() {
    command="$1"
    eval "$command" &
}

current_workspace=$(get_value "wmctrl -d | grep '*' | awk '{print $1}'")
wlist_ids=$(get_value "wmctrl -l")
relevant=()

while read -r item; do
    workspace=$(echo "$item" | awk '{print $2}')
    if [ "$workspace" = "*" ]; then
        relevant+=("$item")
    fi
done <<< "$wlist_ids"

panel=()

for item in "${relevant[@]}"; do
    item_id=$(echo "$item" | awk '{print $1}')
    data=$(get_value "xprop -id $item_id")
    if [ $(echo "$data" | grep -c "_TYPE_NORMAL") -eq 1 ] || [ $(echo "$data" | grep -c "TYPE_DIALOG") -eq 1 ]; then
        panel+=("$item_id")
    fi
done

if [ $# -ge 1 ]; then
    index=$(( $1 - 1 ))
    if [ $index -ge 0 ] && [ $index -lt ${#panel[@]} ]; then
        window="${panel[$index]}"
        run_command "wmctrl -ia $window"
    fi
fi
